### ISSUE TITLE
Dependabot

### ISSUE THREAD

**Issue by chmouel** [openshift-pipelines/opc#3]
maybe not dependabot dependabot or maybe dependabot but only on tkn/tkn-pac

but in any case we need some sort of pull request opener when there is a new tkn/tkn-pac version trying to bump it and see how things goes, at least for notifications that we need to bump

**Comment by vdemeester** [comment]
I enabled dependabot on the repo, let's see how it acts.

**Comment by chmouel** [comment]
the idea was dependabot only on tekton/cli and openshift-pipelines/pac, getting notifed abotu other update is not only not worth it but can break when we update pac/cli

**Comment by vdemeester** [comment]
@chmouel I know 🙃 I think dependabot can be "smart" enough and only bump *direct* dependencies (and thus only pac and tektoncd/cli). I did set it up weekly, so we'll see how it act soon-ish, and we can disable if it gets too much in the way.

**Comment by chmouel** [comment]
if you know then what is the point to enabling it ? just so to generate noise? 🙃
